server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ShailashreeKrishna/cloud-configuration-2022.git
          search-paths:
          - '{application}'

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
          
          